// <auto-generated />
namespace MedicoLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Crearbasededatos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Crearbasededatos));
        
        string IMigrationMetadata.Id
        {
            get { return "202211142259279_Crear base de datos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
